# This yml file containerized the fastapi app and connects a postgres db in the local machine.
# remove "-local-db" from name to execute

version: '3.8'

services:
  my_web:
    container_name: fastapi_app
    build: .
    command: sh -c "uvicorn main:app --host=0.0.0.0 --port=8000 --reload"
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
    restart: always
