version: '3.8'

services:
  my_web:
    container_name: fastapi_app
    build: .  # path of the Dockerfile
    command: sh -c "uvicorn main:app --host=0.0.0.0 --port=8000 --reload"
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
    restart: always
    depends_on:
      - my_pg_db

  my_pg_db:
    image: postgres:alpine
    container_name: postgres_for_fastapi
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    # networks:  # For custom networks.
    #   - my_network

# networks:
#   my_network:
#     driver: bridge